---
name: Generate Code from AWS documentation

on:
  schedule:
    # Why 1:57 not and 2:00? Because most hourly jobs probably run at the hour.
    # Keeping concurrent jobs low reduces hardware requirements, being nice to
    # GitHub and the environment.
    - cron: 57 1 * * *
  workflow_dispatch:
    inputs:
      command:
        description: make command to run
        required: true
        default: generate

jobs:
  generate:
    runs-on: ubuntu-latest
    container: ubuntu:18.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Generate code
        uses: udondan/cdk-nodejs@v0.2.0
        with:
          args: make generate
        if: ${{ github.event_name == 'schedule' }}

      - name: Generate code
        uses: udondan/cdk-nodejs@v0.2.0
        with:
          args: make ${{ github.event.inputs.command }}
        if: ${{ github.event_name == 'workflow_dispatch' }}

      - name: Commit and push changes
        run: |
          set -x
          test -e lib/index.ts || exit 1
          apt update
          apt-get install -y git
          git diff --quiet || (
            apt-get install -y pcregrep make &&
            perl -pi -e 's/^(\d+\.)(\d+)(\.\d+)$/($1).($2+1).".0"/e' VERSION &&
            make update-version-refs &&
            make stats &&
            make changelog &&
            git add CHANGELOG/* &&
            make regenerate-code-example-results &&
            git config --local user.email "deemes79@googlemail.com" &&
            git config --local user.name "udondan" &&
            rm -rf node_modules tsconfig.json &&
            git add * &&
            git commit -m "Adds latest IAM updates from AWS" &&
            git push "https://udondan:${{ secrets.OVERRIDE_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:main
          )
