---
name: Release

on:
  push:
    branches:
      - main
    paths:
      - VERSION
  workflow_dispatch:

jobs:
  test:
    name: Test package
    runs-on: ubuntu-latest
    container:
      image: jsii/superchain
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(cat VERSION)

      - name: Build source
        uses: udondan/jsii-publish@v0.10.0
        with:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
          BUILD_SOURCE: true

      - name: Build packages
        uses: udondan/jsii-publish@v0.10.0
        with:
          BUILD_PACKAGES: true

      - name: Test Python package
        run: make test-python

      - name: Build CDK variant
        run: make cdk

      - name: Build source
        uses: udondan/jsii-publish@v0.10.0
        with:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
          BUILD_SOURCE: true

      - name: Build packages
        uses: udondan/jsii-publish@v0.10.0
        with:
          BUILD_PACKAGES: true

      - name: Test Python package
        run: make test-python-cdk

  release:
    name: Create release
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(cat VERSION)

      - name: Update Readme
        uses: udondan/ver2doc@v1.0.1
        with:
          FILE: README.md
          PATTERN: (iam-floyd\@|maven-v)[0-9.]+
          REPLACE: \${1}${VERSION}

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git diff --exit-code || git commit -m "Finalize v${{ steps.get_version.outputs.VERSION }}" -a

      - name: Push changes
        run: >
          [[ "${{ github.ref }}" == refs/tags/* ]] ||
          git push "https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}.git" HEAD:${{ github.ref }}

      - name: Create tag
        run: |
          git config --local user.email "deemes79@googlemail.com"
          git config --local user.name "udondan"
          git tag -a "v$(cat VERSION)" -m "Creates tag v$(cat VERSION)"
          git push "https://udondan:${{ secrets.OVERRIDE_TOKEN }}@github.com/${{ github.repository }}.git" --tags
          touch CHANGELOG/v${{ steps.get_version.outputs.VERSION }}.md

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: v${{ steps.get_version.outputs.VERSION }}
          body_path: CHANGELOG/v${{ steps.get_version.outputs.VERSION }}.md
